// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentMonitoring.proto



import com.google.protobuf.AbstractMessage;

public final class EnvironmentMonitoringProtos {
  private EnvironmentMonitoringProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EnvironmentUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnvironmentUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord>
        getSensorRecordList();
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getSensorRecord(int index);
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    int getSensorRecordCount();
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder>
        getSensorRecordOrBuilderList();
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder getSensorRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code EnvironmentUpdate}
   */
  public static final class EnvironmentUpdate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EnvironmentUpdate)
      EnvironmentUpdateOrBuilder {
    // Use EnvironmentUpdate.newBuilder() to construct.
    private EnvironmentUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnvironmentUpdate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnvironmentUpdate defaultInstance;
    public static EnvironmentUpdate getDefaultInstance() {
      return defaultInstance;
    }

    public EnvironmentUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnvironmentUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sensorRecord_ = new java.util.ArrayList<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              sensorRecord_.add(input.readMessage(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sensorRecord_ = java.util.Collections.unmodifiableList(sensorRecord_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnvironmentMonitoringProtos.EnvironmentUpdate.class, EnvironmentMonitoringProtos.EnvironmentUpdate.Builder.class);
    }

    public static com.google.protobuf.Parser<EnvironmentUpdate> PARSER =
        new com.google.protobuf.AbstractParser<EnvironmentUpdate>() {
      public EnvironmentUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvironmentUpdate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnvironmentUpdate> getParserForType() {
      return PARSER;
    }

    public interface SensorRecordOrBuilder extends
        // @@protoc_insertion_point(interface_extends:EnvironmentUpdate.SensorRecord)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional double latitude = 2;</code>
       */
      boolean hasLatitude();
      /**
       * <code>optional double latitude = 2;</code>
       */
      double getLatitude();

      /**
       * <code>optional double longitude = 3;</code>
       */
      boolean hasLongitude();
      /**
       * <code>optional double longitude = 3;</code>
       */
      double getLongitude();

      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      long getTimestamp();

      /**
       * <code>optional float carbon_monoxide = 20;</code>
       */
      boolean hasCarbonMonoxide();
      /**
       * <code>optional float carbon_monoxide = 20;</code>
       */
      float getCarbonMonoxide();

      /**
       * <code>optional float particulate_matter = 40;</code>
       */
      boolean hasParticulateMatter();
      /**
       * <code>optional float particulate_matter = 40;</code>
       */
      float getParticulateMatter();

      /**
       * <code>optional float temperature = 60;</code>
       */
      boolean hasTemperature();
      /**
       * <code>optional float temperature = 60;</code>
       */
      float getTemperature();

      /**
       * <code>optional float relative_humidity = 80;</code>
       */
      boolean hasRelativeHumidity();
      /**
       * <code>optional float relative_humidity = 80;</code>
       */
      float getRelativeHumidity();

      /**
       * <code>optional float ultraviolet = 100;</code>
       */
      boolean hasUltraviolet();
      /**
       * <code>optional float ultraviolet = 100;</code>
       */
      float getUltraviolet();
    }
    /**
     * Protobuf type {@code EnvironmentUpdate.SensorRecord}
     */
    public static final class SensorRecord extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:EnvironmentUpdate.SensorRecord)
        SensorRecordOrBuilder {
      // Use SensorRecord.newBuilder() to construct.
      private SensorRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SensorRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SensorRecord defaultInstance;
      public static SensorRecord getDefaultInstance() {
        return defaultInstance;
      }

      public SensorRecord getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SensorRecord(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 17: {
                bitField0_ |= 0x00000001;
                latitude_ = input.readDouble();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000002;
                longitude_ = input.readDouble();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000004;
                timestamp_ = input.readInt64();
                break;
              }
              case 165: {
                bitField0_ |= 0x00000008;
                carbonMonoxide_ = input.readFloat();
                break;
              }
              case 325: {
                bitField0_ |= 0x00000010;
                particulateMatter_ = input.readFloat();
                break;
              }
              case 485: {
                bitField0_ |= 0x00000020;
                temperature_ = input.readFloat();
                break;
              }
              case 645: {
                bitField0_ |= 0x00000040;
                relativeHumidity_ = input.readFloat();
                break;
              }
              case 805: {
                bitField0_ |= 0x00000080;
                ultraviolet_ = input.readFloat();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.class, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder.class);
      }

      public static com.google.protobuf.Parser<SensorRecord> PARSER =
          new com.google.protobuf.AbstractParser<SensorRecord>() {
        public SensorRecord parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SensorRecord(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SensorRecord> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int LATITUDE_FIELD_NUMBER = 2;
      private double latitude_;
      /**
       * <code>optional double latitude = 2;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double latitude = 2;</code>
       */
      public double getLatitude() {
        return latitude_;
      }

      public static final int LONGITUDE_FIELD_NUMBER = 3;
      private double longitude_;
      /**
       * <code>optional double longitude = 3;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double longitude = 3;</code>
       */
      public double getLongitude() {
        return longitude_;
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 4;
      private long timestamp_;
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }

      public static final int CARBON_MONOXIDE_FIELD_NUMBER = 20;
      private float carbonMonoxide_;
      /**
       * <code>optional float carbon_monoxide = 20;</code>
       */
      public boolean hasCarbonMonoxide() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float carbon_monoxide = 20;</code>
       */
      public float getCarbonMonoxide() {
        return carbonMonoxide_;
      }

      public static final int PARTICULATE_MATTER_FIELD_NUMBER = 40;
      private float particulateMatter_;
      /**
       * <code>optional float particulate_matter = 40;</code>
       */
      public boolean hasParticulateMatter() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float particulate_matter = 40;</code>
       */
      public float getParticulateMatter() {
        return particulateMatter_;
      }

      public static final int TEMPERATURE_FIELD_NUMBER = 60;
      private float temperature_;
      /**
       * <code>optional float temperature = 60;</code>
       */
      public boolean hasTemperature() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float temperature = 60;</code>
       */
      public float getTemperature() {
        return temperature_;
      }

      public static final int RELATIVE_HUMIDITY_FIELD_NUMBER = 80;
      private float relativeHumidity_;
      /**
       * <code>optional float relative_humidity = 80;</code>
       */
      public boolean hasRelativeHumidity() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional float relative_humidity = 80;</code>
       */
      public float getRelativeHumidity() {
        return relativeHumidity_;
      }

      public static final int ULTRAVIOLET_FIELD_NUMBER = 100;
      private float ultraviolet_;
      /**
       * <code>optional float ultraviolet = 100;</code>
       */
      public boolean hasUltraviolet() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional float ultraviolet = 100;</code>
       */
      public float getUltraviolet() {
        return ultraviolet_;
      }

      private void initFields() {
        latitude_ = 0D;
        longitude_ = 0D;
        timestamp_ = 0L;
        carbonMonoxide_ = 0F;
        particulateMatter_ = 0F;
        temperature_ = 0F;
        relativeHumidity_ = 0F;
        ultraviolet_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(2, latitude_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(3, longitude_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(4, timestamp_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeFloat(20, carbonMonoxide_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeFloat(40, particulateMatter_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeFloat(60, temperature_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeFloat(80, relativeHumidity_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeFloat(100, ultraviolet_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, latitude_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, longitude_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, timestamp_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(20, carbonMonoxide_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(40, particulateMatter_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(60, temperature_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(80, relativeHumidity_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(100, ultraviolet_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code EnvironmentUpdate.SensorRecord}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:EnvironmentUpdate.SensorRecord)
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.class, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder.class);
        }

        // Construct using hk.edu.polyu.comp.sensorlibrary.EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          latitude_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          longitude_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          timestamp_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          carbonMonoxide_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000008);
          particulateMatter_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000010);
          temperature_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000020);
          relativeHumidity_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000040);
          ultraviolet_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000080);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_descriptor;
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getDefaultInstanceForType() {
          return EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance();
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord build() {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord result = buildPartial();
          if (!result.isInitialized()) {
            throw AbstractMessage.Builder.newUninitializedMessageException(result);
          }
          return result;
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord buildPartial() {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord result = new EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.latitude_ = latitude_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.longitude_ = longitude_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.carbonMonoxide_ = carbonMonoxide_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.particulateMatter_ = particulateMatter_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.temperature_ = temperature_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.relativeHumidity_ = relativeHumidity_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.ultraviolet_ = ultraviolet_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord) {
            return mergeFrom((EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord other) {
          if (other == EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance()) return this;
          if (other.hasLatitude()) {
            setLatitude(other.getLatitude());
          }
          if (other.hasLongitude()) {
            setLongitude(other.getLongitude());
          }
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasCarbonMonoxide()) {
            setCarbonMonoxide(other.getCarbonMonoxide());
          }
          if (other.hasParticulateMatter()) {
            setParticulateMatter(other.getParticulateMatter());
          }
          if (other.hasTemperature()) {
            setTemperature(other.getTemperature());
          }
          if (other.hasRelativeHumidity()) {
            setRelativeHumidity(other.getRelativeHumidity());
          }
          if (other.hasUltraviolet()) {
            setUltraviolet(other.getUltraviolet());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private double latitude_ ;
        /**
         * <code>optional double latitude = 2;</code>
         */
        public boolean hasLatitude() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional double latitude = 2;</code>
         */
        public double getLatitude() {
          return latitude_;
        }
        /**
         * <code>optional double latitude = 2;</code>
         */
        public Builder setLatitude(double value) {
          bitField0_ |= 0x00000001;
          latitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double latitude = 2;</code>
         */
        public Builder clearLatitude() {
          bitField0_ = (bitField0_ & ~0x00000001);
          latitude_ = 0D;
          onChanged();
          return this;
        }

        private double longitude_ ;
        /**
         * <code>optional double longitude = 3;</code>
         */
        public boolean hasLongitude() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional double longitude = 3;</code>
         */
        public double getLongitude() {
          return longitude_;
        }
        /**
         * <code>optional double longitude = 3;</code>
         */
        public Builder setLongitude(double value) {
          bitField0_ |= 0x00000002;
          longitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double longitude = 3;</code>
         */
        public Builder clearLongitude() {
          bitField0_ = (bitField0_ & ~0x00000002);
          longitude_ = 0D;
          onChanged();
          return this;
        }

        private long timestamp_ ;
        /**
         * <code>optional int64 timestamp = 4;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 timestamp = 4;</code>
         */
        public long getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>optional int64 timestamp = 4;</code>
         */
        public Builder setTimestamp(long value) {
          bitField0_ |= 0x00000004;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 timestamp = 4;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000004);
          timestamp_ = 0L;
          onChanged();
          return this;
        }

        private float carbonMonoxide_ ;
        /**
         * <code>optional float carbon_monoxide = 20;</code>
         */
        public boolean hasCarbonMonoxide() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional float carbon_monoxide = 20;</code>
         */
        public float getCarbonMonoxide() {
          return carbonMonoxide_;
        }
        /**
         * <code>optional float carbon_monoxide = 20;</code>
         */
        public Builder setCarbonMonoxide(float value) {
          bitField0_ |= 0x00000008;
          carbonMonoxide_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float carbon_monoxide = 20;</code>
         */
        public Builder clearCarbonMonoxide() {
          bitField0_ = (bitField0_ & ~0x00000008);
          carbonMonoxide_ = 0F;
          onChanged();
          return this;
        }

        private float particulateMatter_ ;
        /**
         * <code>optional float particulate_matter = 40;</code>
         */
        public boolean hasParticulateMatter() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional float particulate_matter = 40;</code>
         */
        public float getParticulateMatter() {
          return particulateMatter_;
        }
        /**
         * <code>optional float particulate_matter = 40;</code>
         */
        public Builder setParticulateMatter(float value) {
          bitField0_ |= 0x00000010;
          particulateMatter_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float particulate_matter = 40;</code>
         */
        public Builder clearParticulateMatter() {
          bitField0_ = (bitField0_ & ~0x00000010);
          particulateMatter_ = 0F;
          onChanged();
          return this;
        }

        private float temperature_ ;
        /**
         * <code>optional float temperature = 60;</code>
         */
        public boolean hasTemperature() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional float temperature = 60;</code>
         */
        public float getTemperature() {
          return temperature_;
        }
        /**
         * <code>optional float temperature = 60;</code>
         */
        public Builder setTemperature(float value) {
          bitField0_ |= 0x00000020;
          temperature_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float temperature = 60;</code>
         */
        public Builder clearTemperature() {
          bitField0_ = (bitField0_ & ~0x00000020);
          temperature_ = 0F;
          onChanged();
          return this;
        }

        private float relativeHumidity_ ;
        /**
         * <code>optional float relative_humidity = 80;</code>
         */
        public boolean hasRelativeHumidity() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional float relative_humidity = 80;</code>
         */
        public float getRelativeHumidity() {
          return relativeHumidity_;
        }
        /**
         * <code>optional float relative_humidity = 80;</code>
         */
        public Builder setRelativeHumidity(float value) {
          bitField0_ |= 0x00000040;
          relativeHumidity_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float relative_humidity = 80;</code>
         */
        public Builder clearRelativeHumidity() {
          bitField0_ = (bitField0_ & ~0x00000040);
          relativeHumidity_ = 0F;
          onChanged();
          return this;
        }

        private float ultraviolet_ ;
        /**
         * <code>optional float ultraviolet = 100;</code>
         */
        public boolean hasUltraviolet() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional float ultraviolet = 100;</code>
         */
        public float getUltraviolet() {
          return ultraviolet_;
        }
        /**
         * <code>optional float ultraviolet = 100;</code>
         */
        public Builder setUltraviolet(float value) {
          bitField0_ |= 0x00000080;
          ultraviolet_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float ultraviolet = 100;</code>
         */
        public Builder clearUltraviolet() {
          bitField0_ = (bitField0_ & ~0x00000080);
          ultraviolet_ = 0F;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:EnvironmentUpdate.SensorRecord)
      }

      static {
        defaultInstance = new SensorRecord(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:EnvironmentUpdate.SensorRecord)
    }

    public static final int SENSOR_RECORD_FIELD_NUMBER = 1;
    private java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> sensorRecord_;
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> getSensorRecordList() {
      return sensorRecord_;
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder>
        getSensorRecordOrBuilderList() {
      return sensorRecord_;
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public int getSensorRecordCount() {
      return sensorRecord_.size();
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getSensorRecord(int index) {
      return sensorRecord_.get(index);
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder getSensorRecordOrBuilder(
        int index) {
      return sensorRecord_.get(index);
    }

    private void initFields() {
      sensorRecord_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sensorRecord_.size(); i++) {
        output.writeMessage(1, sensorRecord_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sensorRecord_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sensorRecord_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EnvironmentMonitoringProtos.EnvironmentUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EnvironmentUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnvironmentUpdate)
        EnvironmentMonitoringProtos.EnvironmentUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentMonitoringProtos.EnvironmentUpdate.class, EnvironmentMonitoringProtos.EnvironmentUpdate.Builder.class);
      }

      // Construct using hk.edu.polyu.comp.sensorlibrary.EnvironmentMonitoringProtos.EnvironmentUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSensorRecordFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sensorRecordBuilder_ == null) {
          sensorRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sensorRecordBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_descriptor;
      }

      public EnvironmentMonitoringProtos.EnvironmentUpdate getDefaultInstanceForType() {
        return EnvironmentMonitoringProtos.EnvironmentUpdate.getDefaultInstance();
      }

      public EnvironmentMonitoringProtos.EnvironmentUpdate build() {
        EnvironmentMonitoringProtos.EnvironmentUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public EnvironmentMonitoringProtos.EnvironmentUpdate buildPartial() {
        EnvironmentMonitoringProtos.EnvironmentUpdate result = new EnvironmentMonitoringProtos.EnvironmentUpdate(this);
        int from_bitField0_ = bitField0_;
        if (sensorRecordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sensorRecord_ = java.util.Collections.unmodifiableList(sensorRecord_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sensorRecord_ = sensorRecord_;
        } else {
          result.sensorRecord_ = sensorRecordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnvironmentMonitoringProtos.EnvironmentUpdate) {
          return mergeFrom((EnvironmentMonitoringProtos.EnvironmentUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnvironmentMonitoringProtos.EnvironmentUpdate other) {
        if (other == EnvironmentMonitoringProtos.EnvironmentUpdate.getDefaultInstance()) return this;
        if (sensorRecordBuilder_ == null) {
          if (!other.sensorRecord_.isEmpty()) {
            if (sensorRecord_.isEmpty()) {
              sensorRecord_ = other.sensorRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSensorRecordIsMutable();
              sensorRecord_.addAll(other.sensorRecord_);
            }
            onChanged();
          }
        } else {
          if (!other.sensorRecord_.isEmpty()) {
            if (sensorRecordBuilder_.isEmpty()) {
              sensorRecordBuilder_.dispose();
              sensorRecordBuilder_ = null;
              sensorRecord_ = other.sensorRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sensorRecordBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSensorRecordFieldBuilder() : null;
            } else {
              sensorRecordBuilder_.addAllMessages(other.sensorRecord_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EnvironmentMonitoringProtos.EnvironmentUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EnvironmentMonitoringProtos.EnvironmentUpdate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> sensorRecord_ =
        java.util.Collections.emptyList();
      private void ensureSensorRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sensorRecord_ = new java.util.ArrayList<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord>(sensorRecord_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder> sensorRecordBuilder_;

      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> getSensorRecordList() {
        if (sensorRecordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sensorRecord_);
        } else {
          return sensorRecordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public int getSensorRecordCount() {
        if (sensorRecordBuilder_ == null) {
          return sensorRecord_.size();
        } else {
          return sensorRecordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getSensorRecord(int index) {
        if (sensorRecordBuilder_ == null) {
          return sensorRecord_.get(index);
        } else {
          return sensorRecordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder setSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord value) {
        if (sensorRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorRecordIsMutable();
          sensorRecord_.set(index, value);
          onChanged();
        } else {
          sensorRecordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder setSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder builderForValue) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.set(index, builderForValue.build());
          onChanged();
        } else {
          sensorRecordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord value) {
        if (sensorRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorRecordIsMutable();
          sensorRecord_.add(value);
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord value) {
        if (sensorRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorRecordIsMutable();
          sensorRecord_.add(index, value);
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder builderForValue) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.add(builderForValue.build());
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder builderForValue) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.add(index, builderForValue.build());
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addAllSensorRecord(
          java.lang.Iterable<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> values) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sensorRecord_);
          onChanged();
        } else {
          sensorRecordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder clearSensorRecord() {
        if (sensorRecordBuilder_ == null) {
          sensorRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sensorRecordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder removeSensorRecord(int index) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.remove(index);
          onChanged();
        } else {
          sensorRecordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder getSensorRecordBuilder(
          int index) {
        return getSensorRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder getSensorRecordOrBuilder(
          int index) {
        if (sensorRecordBuilder_ == null) {
          return sensorRecord_.get(index);  } else {
          return sensorRecordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder>
           getSensorRecordOrBuilderList() {
        if (sensorRecordBuilder_ != null) {
          return sensorRecordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sensorRecord_);
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder addSensorRecordBuilder() {
        return getSensorRecordFieldBuilder().addBuilder(
            EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder addSensorRecordBuilder(
          int index) {
        return getSensorRecordFieldBuilder().addBuilder(
            index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder>
           getSensorRecordBuilderList() {
        return getSensorRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder>
          getSensorRecordFieldBuilder() {
        if (sensorRecordBuilder_ == null) {
          sensorRecordBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder>(
                  sensorRecord_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sensorRecord_ = null;
        }
        return sensorRecordBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:EnvironmentUpdate)
    }

    static {
      defaultInstance = new EnvironmentUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EnvironmentUpdate)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EnvironmentUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentUpdate_SensorRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033EnvironmentMonitoring.proto\"\216\002\n\021Enviro" +
      "nmentUpdate\0226\n\rsensor_record\030\001 \003(\0132\037.Env" +
      "ironmentUpdate.SensorRecord\032\300\001\n\014SensorRe" +
      "cord\022\020\n\010latitude\030\002 \001(\001\022\021\n\tlongitude\030\003 \001(" +
      "\001\022\021\n\ttimestamp\030\004 \001(\003\022\027\n\017carbon_monoxide\030" +
      "\024 \001(\002\022\032\n\022particulate_matter\030( \001(\002\022\023\n\013tem" +
      "perature\030< \001(\002\022\031\n\021relative_humidity\030P \001(" +
      "\002\022\023\n\013ultraviolet\030d \001(\002B>\n\037hk.edu.polyu.c" +
      "omp.sensorlibraryB\033EnvironmentMonitoring" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnvironmentUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnvironmentUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EnvironmentUpdate_descriptor,
        new java.lang.String[] { "SensorRecord", });
    internal_static_EnvironmentUpdate_SensorRecord_descriptor =
      internal_static_EnvironmentUpdate_descriptor.getNestedTypes().get(0);
    internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EnvironmentUpdate_SensorRecord_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Timestamp", "CarbonMonoxide", "ParticulateMatter", "Temperature", "RelativeHumidity", "Ultraviolet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
